product/urls.py
#Import from the core django
from django.urls import path
#Import from local app/library
from product import views

urlpatterns = [
    #home page
    path('',views.product_list,name='product.list'),
    path('create',views.product_create,name='product.create'),
    path('update/<int:pk>',views.product_update,name='product.update'),
    path('delete/<int:pk>',views.product_delete,name='product.delete'),
    path('view/<int:pk>',views.product_view,name='product.view'),

    #cart
    path('cart',views.viewcart,name='cart'),
    path('addtocart',views.addtocart,name='add.to.cart'),
    path('removefromcart',views.cart_remove,name='remove.from.cart'),
    path('cart/order',views.order_create,name='cart.order'),

    #api
    path('api/get',views.product_list_api),
    
    # order list
    path('api/order_list/<int:pk>',views.order_list_api),
    path('order_list/<int:pk>',views.order_list,name='order.list'),

    #order detail
    path('order_list/details/<int:pk>',views.order_detail_view,name='order.detail'),

    #rating
    path('rating/<int:pk>',views.rating,name='rating'),

    #order status
    path('order_status/<int:pk>',views.order_status,name='order.status'),

]

zinfog/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('product.urls')),
    path('accounts/',include('accounts.urls')),
    path('api-token-auth', views.obtain_auth_token)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
#Import from the core django
from django.db import models
from django.contrib.auth.models import User
#Import from the third library
import datetime

# Create your models here.

#menu
class Product(models.Model):
    title = models.CharField(max_length=300,unique=True)
    image=models.ImageField(upload_to='product', blank=True,null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.IntegerField(null=True,blank=True)
 
    def __str__(self):
        return self.title

class Customer(models.Model):
    name=models.CharField(max_length=300)
    address=models.CharField(max_length=3000)
    mail_id=models.EmailField(null=True,blank=True)
 
    def __str__(self):
        return self.name


#order
class Order(models.Model):
    APPROVED = 0
    SHIPPED = 1
    DELIVERED = 2
    
    ORDER_CHOICES = (
                     (APPROVED, 'approved'),
                     (SHIPPED, 'shipped'),
                     (DELIVERED, 'delivered'),
                     )
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='customer')
    order_status=models.IntegerField(choices=ORDER_CHOICES,default=APPROVED,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user')
    order_date=models.DateField( default=datetime.date.today, blank=True)
    
    def __str__(self):
        return str(f"{self.id}-{self.customer}" )  

#order details
class OrderDetail(models.Model):
 
    order_id=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='order')
    product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='product')
    qty=models.IntegerField()
    total=models.DecimalField(max_digits=10, decimal_places=2)
 
    def __str__(self):
        return str(self.order_id )           

product/forms.py
#Import from the core django
from django import forms
#Import from local app/library
from .models import Product,Order,Customer

#Product
class ProductForm(forms.ModelForm):
    class Meta:
        model= Product
        fields= '__all__'

#Order
class OrderForm(forms.ModelForm):
      class Meta:
        model= Customer
        fields= '__all__'
        # fields=  ['address' , 'mail_id' ]     

class StatusForm(forms.ModelForm):
      class Meta:
        model=Order
        # fields= '__all__'
        fields=  ['order_status']       
        
          

product/views.py
#Import from the core django
from django.shortcuts import render
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.http import JsonResponse,HttpResponse
from django.template import loader
from django.contrib import messages
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse
#Import from the third library
from rest_framework.decorators import api_view
from rest_framework.response import Response
import requests
from datetime import datetime

#Import from local app/library
from product.forms import ProductForm ,OrderForm,StatusForm
from product.models import Product,OrderDetail,Order,Customer
from product.serializers import Productserializers,Orderserializers 



# Create your views here.


@api_view(['GET'])
def product_list_api(request):
    if request.method=='GET':
        val=Product.objects.all()
        print(val)
        serializer=Productserializers(val, many=True)
        return Response(serializer.data)



#View for Product list
def product_list(request):
    response = requests.get('http://127.0.0.1:8000/api/get')
    products = response.json()
    context= {'products':products,"today":datetime.today(),}
    return render(request, 'product/product_list.html',context)

@api_view(['GET'])
def order_list_api(request,pk):
    if request.method=='GET':
        
        # customer=Customer.objects.get(pk=pk)
        # print(customer)
        # orders=Order.objects.filter(customer=customer)
        # print(orders)
        # val=[]
        # for customer_order in customer_orders:
        #     order_details=OrderDetail.objects.filter(order_id=customer_order.id)
        #     val.append(order_details)
        # print(val)   
        user=User.objects.get(pk=pk) 
        # user=self.request.user
        # print(user)
        orders=Order.objects.filter(user=user)
        # print(orders)
        serializer=Orderserializers(orders,many=True)
        return Response(serializer.data)

#View for Product list
def order_list(request,pk):
    # print(request)
    response = requests.get('http://127.0.0.1:8000/api/order_list/'+str(pk))
    # print(response)
    orders = response.json()
    # print(orders)
    context= {'orders':orders}
    return render(request, 'product/order_list.html',context)    




#View for Create Product
@login_required
def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect("product.list")        
    else:
        form = ProductForm()

    context = {'form': form}
    return render(request,'product/product_edit.html',context) 

#View for edit product 
@login_required
def product_update(request,pk):
    product=Product.objects.get(id=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST,files=request.FILES,instance=product)
        if form.is_valid():
            form.save()
            return redirect("product.list",)
    else:
        form = ProductForm(instance=product)
    context = {'form': form,'product': product}
    return render(request,'product/product_edit.html',context) 

#View for product delete
@login_required
def product_delete(request, pk):
    data = dict()
    
    if request.method == 'POST':
        product = Product.objects.get(pk=pk)
        product.delete()
        return redirect('product.list') 
        # data['form_is_valid'] = True
        # products=Product.objects.all() 
        # data['html_product_list'] = render_to_string('product/partial_product_list.html', {
        #         'products': products
        #     })
        
    else:
        product = Product.objects.get(pk=pk)
        context = {'product': product}
        data['html_form'] = render_to_string('product/partial_product_delete.html',
        context,
        request=request,
    )

        return JsonResponse(data) 

#view for product detail view
def product_view(request,pk):
    product=Product.objects.get(pk=pk)    
    context={'product':product}   
    return render(request,'product/product_view.html',context)     

#add to cart view
def addtocart(request):
    productid = request.GET['productid']
    qty = request.GET['qty']
    cartitems = {}
    if request.session.__contains__('cartdata'):
        cartitems = request.session['cartdata']
    cartitems[productid]=qty
    request.session['cartdata'] = cartitems
    current_item=Product.objects.get(pk=productid)

    products=Product.objects.all()     
    context={'products':products,
            "today":datetime.today(),
            } 
    return render(request,'product/product_list.html',context)


#to remove cart item
def cart_remove(request):
    print(request)
    productid = request.GET['productid']
    cartitems = {}
    if request.session.__contains__('cartdata'):
        cartitems = request.session['cartdata']
    request.session['cartdata'] = cartitems
    # print( request.session['cartdata'])
    del cartitems[productid]
    return redirect('cart')    
     
#View for order create
@login_required
def order_create(request):
    data = dict()
    if request.method == 'POST':

        form = OrderForm(request.POST,files=request.FILES)
        if form.is_valid():
            print(form.errors)
            customer=form.save()
            orderd_user=request.user
            order=Order.objects.create(customer=customer,user=orderd_user)
            order_id=Order.objects.get(pk=order.id)
            cartitems = {}
            if request.session.__contains__('cartdata'):
                cartitems = request.session['cartdata']
            request.session['cartdata'] = cartitems
            val=request.session['cartdata']
            for key,value in (zip((val.keys()), (val.values()))):
                product=Product.objects.get(pk=key)
                order_detail=OrderDetail.objects.create(order_id=order_id,product=product,qty=value,total=int(value)*product.price)
           
            subject = f'INVOICE -{customer}'
            with open('message.txt','r') as f:
                f=f.read()
                message=f

            email_from = settings.EMAIL_HOST_USER
            recipient_list = [customer.mail_id]
    

            send_mail( subject, message, email_from, recipient_list )

            cartitems.clear()
            messages.success(request, 'Order Placed Successfully')
            return redirect("product.list")        
    else:
        form = OrderForm()

    context = {'form': form}
    data['html_form'] = render_to_string('product/order.html',context,request=request,)
    return JsonResponse(data)  
       


#cart view
def viewcart(request):
    page = loader.get_template("product/shoppingcart.html") 
    if request.session.__contains__('cartdata'):
        # for key in request.session.keys():
            it = request.session['cartdata'].items()
            productdb =[]
            it = list(it)   
            for i in range(len(it)):
                productid = it[i][0]
                qty = it[i][1]
                db = Product.objects.get(id=productid)
                productdb.append({
                    'id':productid,
                    'title':db.title,
                    'Qty':qty,
                    'Price':db.price,
                    "total_price":int(qty)*db.price
                })
            fullamount = []
            for i in productdb:
                for key,value in i.items():
                    if key == "total_price":
                        fullamount.append(value)
            
            data = {"products":productdb,"full_amount":sum(fullamount)}
            response = page.render(data,request)
            return HttpResponse(response)
    else:
        # return HttpResponse("No item added!!")
        return render(request,'product/shoppingcart.html') 
@login_required
def rating(request,pk):
    print(request.POST)
    product=Product.objects.get(pk=pk)
    rating=e=request.POST['rating']
    if rating :
        product.rating=request.POST['rating']
        product.save()
        return HttpResponseRedirect(reverse('product.view',args=[pk]))
    else:
        return HttpResponseRedirect(reverse('product.view',args=[pk]))


def order_detail_view(request,pk):
    order_details=OrderDetail.objects.filter(order_id=pk)
    # print(order_details)
    order=Order.objects.get(pk=pk)
    form=StatusForm(instance=order)
    context={'order_details':order_details,'pk':pk,'form':form}

    return render(request,'product/order_detail.html',context) 

def order_status(request,pk):
    print(request)
    if request.method== 'POST':
        status=request.POST['order_status']
        order=Order.objects.get(pk=pk)
        order.order_status=status
        order.save()

    return HttpResponseRedirect(reverse('order.detail',args=[pk]))

templates/product/order.html
<form method="post" action="{% url 'cart.order' %}" class="">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title"><strong>Delivery Address </strong></h4>
      <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    
    </div>
    <div class="modal-body">
      {{form.as_p}}
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" id="btn3">Submit</button>
      </div>
</form>






  
 

templates/product/order_detail.html
{% extends 'base.html' %}
{% block content %}
<h2 style="color: blue;"><b>Order ID:{{pk}}</b></h1>
    <h6>{{today}}</h6>
    <hr>
<table class="table" id="">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Menu</th>
            <th>Qty</th>
            <th>Total Price(Rs)</th>
        </tr>
    </thead>
    <tbody>
    <tr>
    <td style="color: green;"><b>{{ pk}}</b></td>
    </tr>
    {% for order_detail in order_details %}
    <tr>
    <td></td>
    <td>{{ order_detail.product}}</td>
    <td>{{ order_detail.qty }}</td>
    <td>{{ order_detail.total }}</td>
    </tr>
  
{% empty %}
  <tr>
    <td colspan="7" class="text-center bg-warning">There is no orders</td>
  </tr>
  {% endfor %}

  {% comment %} <tr>
    <form method="post" action="{% url 'order.status' pk %}">
        {% csrf_token %}
    <td><b>{{form}}</b></td>
    <td><button class="btn btn-success btn-sm" type="submit">change</button></td>
    </form>
</tr> {% endcomment %}
    </tbody>
</table>
<form method="post" action="{% url 'order.status' pk %}">
{% csrf_token %}
<b>{{form}}</b>
<button class="btn btn-success btn-sm" type="submit">change</button>
</form>
{% endblock %}

templates/product/order_list.html
{% extends 'base.html' %}
{% block content %}
<h2 style="color: blue;"><b>Orders</b></h1>
    <h6>{{today}}</h6>
    <h6>USER: {{user}}</h6>
    <hr>
<table class="table" id="">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Customer ID</th>
            <th>Ordered Date</th>
            <th>Order Status</th>
  
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
    <tr>
    <td style="color: green;"><b><a href="{% url 'order.detail' order.id %}">{{ order.id}}</a></b></td>
    <td>{{ order.customer}}</td>
    <td>{{ order.order_date}}</td>
    <td>{{ order.order_status }}</td>
    </tr>
 
  
{% empty %}
  <tr>
    <td colspan="7" class="text-center bg-warning">There is no orders</td>
  </tr>
  {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/product/partial_order_form.html
{% comment %} {% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %} {% endcomment %}

templates/product/partial_product_delete.html
<form method="post" action="{% url 'product.delete' product.id %}" class="">
    {% csrf_token %}
    <div class="modal-header">
      <h4 class="modal-title">Confirm Product Deletion</h4>
      <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      
    </div>
    <div class="modal-body">
      <p class="lead">Are you sure you want to delete the product <strong>{{ product.title }}</strong>?</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-danger" id="btn3" data-item-id="">Delete Product</button>
    </div>
  </form>

templates/product/partial_product_list.html
{% for product in products %}
  <tr>
    <td><a href="{% url 'product.view' product.id %}">{{ product.title }}</a></td>
    <td>{{ product.price }} Rs</td>
    <td>{{ product.rating }} </td>
    {% comment %} <td>
        <a href="{% url 'product.view' product.id %}"><button type="button"
                class="btn btn-primary btn-sm">
                <i class="fa-regular fa-eye"></i> View
        </button></a>
        <a href="{% url 'product.update' product.id %}"><button type="button"
                class="btn btn-warning btn-sm">
                <i class="fa-solid fa-pen-to-square"></i> Edit
        </button></a>
        <button type="button"
        class="btn btn-danger btn-sm js-delete-product"
        data-url="{% url 'product.delete' product.id %}">
        <i class="fa-solid fa-trash"></i> Delete
        </button>
        
      </td> {% endcomment %}
      <td>
        <form action="/addtocart">
          <input type="hidden"  name="productid" value="{{product.id}}">
          <input class="btn btn-light btn-sm" type="number" value="1" min="1" max="5" name="qty">
          <button class="btn btn-success btn-sm" type="submit"><i class="fa-solid fa-cart-plus"></i>Add To Cart</button>
      </form>
    
      </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="7" class="text-center bg-warning">No Item</td>
  </tr>
{% endfor %}

<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-menu">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>

templates/product/product_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br>
    <div class="row">
        <div class="col">
            <div class="card">
                {% if product.id %}
                <h3 class="card-header"><b>Product Edit Form</u></b></h5>
                {% else %}
                <h3 class="card-header"><b>Product Create Form</b></h5>
                {% endif %}
                <div class="card-body">
                    <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-body">
                            <div class="form-group row">
                               
        
                                <div class="col-md-5">
                                    <label class="form-label" for="id_name">Product</label>
                                    {{form.title}}
                                   
                                </div>
                            </div>

                            <div class="form-group row">
                                
                            
                                <div class="col-md-5">
                                    <label class="form-label" for="price">Price</label>
                                    {{form.price}}
                
                                    
    
                                </div>

                                
                            </div> 
                            <div class="form-group row">
                                
                            
                                <div class="col-md-5">
                                    <label class="form-label" for="id_image">Image</label>
                                    {{form.image}}
                
                                    
    
                                </div>

                                
                            </div> 

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer bg-light">
                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="offset-sm-3 col-md-5">
                                            <button class="btn btn-primary btn-rounded">Submit</button>
                                         
                                            <a href="{% url 'product.list' %}"><button type="button" class="btn btn-secondary clear-form btn-rounded btn-outline">
                                                Cancel
                                            </button></a>
                                            
                                        </div>
                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{%endblock%}

templates/product/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
    <script src="{% static 'js/product.js' %}"></script>
  
{% endblock %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> <h4 style="color: green;"><b>{{ message }} </b></h4></li>
    {% endfor %}
</ul>
{% endif %}

<h1 style="color: green; font-size:3em;"><b>ZINFOG CODELABS</b></h1>
<h5>{{today}}</h5>
<hr>




<table class="table" id="menu-table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Rating</th>
        </tr>
    </thead>

    <tbody>
        {% include 'product/partial_product_list.html' %} 
    </tbody>
</table>

{% endblock %}

templates/product/product_view.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
    <script src="{% static 'js/product.js' %}"></script>
  
{% endblock %}
{% block content %}
<div class="card" style="width: 50rem;">
    
    <div class="card-body" id="product_view">
    {% comment %} <h3><b>ID:            {{item.id}}</b></h3> {% endcomment %}
    {% if product.image %}
    <img src="{{product.image.url}}" alt="{{product.image}}" id="" title="" class="img-fluid" width="250px"//>
    {%else%}
    {%endif%}
    <h3><b> {{product.title}}</b></h3>
    <h3><b>Price:         {{product.price}} Rs</b></h3>
    <h3><b>Rating:      {{product.rating}}</b></h3>
    <table class="table" id="menu-table">
      <thead>
          <tr>
            {% if user.is_authenticated %}
         
              <th><a href="{% url 'product.update' product.id %}"><button type="button"
                class="btn btn-warning btn-sm">
                <i class="fa-solid fa-pen-to-square"></i> Edit
          </button></a></th>
              <th><button type="button"
                class="btn btn-danger btn-sm js-delete-product"
                data-url="{% url 'product.delete' product.id %}">
                <i class="fa-solid fa-trash"></i> Delete
                </button></th>
              <th><form action="/addtocart">
                <input type="hidden"  name="productid" value="{{product.id}}">
                <input class="btn btn-light btn-sm" type="number" value="1" min="1" max="5" name="qty">
                <button class="btn btn-success btn-sm" type="submit"><i class="fa-solid fa-cart-plus"></i>Add To Cart</button>
            </form></th>
            <th><form method="post" action="{% url 'rating' product.id %}">
              {% csrf_token %}
              {% comment %} <input type="hidden"  name="rating" value="{{product.rating}}"> {% endcomment %}
              <input class="btn btn-dark btn-sm" type="number" value="" min="1" max="5" name="rating" placeholder="{{product.rating}}">
              <button class="btn btn-dark btn-sm" type="submit"><i class="fa-solid fa-star"></i>Rating</button>
          </form></th>
          {% else %}
          <p class="navbar-brand" style="color: green;">You are not logged in</p>
          {% endif %}
          </tr>
      </thead>
  
      <tbody>
          
      </tbody>
  </table>
    
    
    

  </div>

  
<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-menu">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>
{%endblock%}

templates/product/shoppingcart.html
{% extends 'base.html' %}
{% load static %}
{% block javascript %}
    <script src="{% static 'js/order.js' %}"></script>
  
{% endblock %}

{% block content %} 
<table class="table" id="cart-table">
  
    <thead>
        <tr>
            <th>ID</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Total price</th>
        </tr>
    </thead>
    {% for product in products %}
    <tr>
        <td>{{ product.id }}</td>
        <td>{{ product.title }}</td>
        <td>{{ product.Qty }}</td>
        <td>{{ product.Price }} Rs</td>
        <td>{{ product.total_price }} Rs</td>
        <td><form action="/removefromcart">
            <input type="hidden"  name="productid" value="{{product.id}}">
            <button type="submit"
                class="btn btn-danger btn-sm">
                <i class="fa-solid fa-trash"></i>
            </button>
        </form>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="7" class="text-center bg-warning">There is no item in the cart</td>
    </tr>
    {% endfor %}
    <tbody>
        
    </tbody>
</table>


    <h4><b>Full Cart Amount:{{full_amount}} Rs</b></h4>
    <form action="{% url 'cart.order'%}" id="placeorder">
        <button type="button"
        class="btn btn-success btn-sm js-order-product"
        data-url="{% url 'cart.order' %}">
        <i class="fa-solid fa-cart-plus"></i> Place Order
        </button>
        {% comment %} <a href="{% url 'cart.order' %}"><button type="button"
        class="btn btn-success btn-sm">
        <i class="fa-solid fa-cart-plus"></i> Place Order
    </button></a> {% endcomment %}
    </form>
    <hr>

<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-cart">
    <div class="modal-dialog">
      <div class="modal-content"></div>
    </div>
</div>    




{% endblock %} 

  